Fixed expand empty not expanding tags with attributes
tafia/quick-xml pull request #704
Opened 2024-01-12 06:23 UTC by M-Valts

In PR #620 the expand_empty_elements function was added to the serializer. With the current implementation only unit variants are expanded, but if a tag has an attribute it would not expand the tag which seems inconsistent.

2024-01-12 09:06 UTC, Mingun requested changes
Could you add tests for that? There are no writer-only tests so I suggest to create `tests/writer-config.rs` and add test for expand option there (it then will be filled with tests for other options as well, similarly to `reader-config.rs`).

2024-01-12 09:06 UTC, Mingun commented on src/se/element.rs
> +                self.ser.ser.writer.write_str("</")?;
```suggestion
                self.ser.ser.writer.write_str("></")?;
```

2024-01-12 09:06 UTC, Mingun commented on Changelog.md
> +- [#704]: Fix empty tags with attributes not being expanded when `expand_empty_elements` is set to true.
You forgot to add actual link in line 70

2024-01-14 18:05 UTC, dralley approved these changes

2024-01-14 19:25 UTC, Mingun commented
Thanks @M-Valts. I still wait tests to ensure that now it works in all situations.

2024-01-21 17:32 UTC, merged

2024-01-21 17:32 UTC, Mingun commented
Thanks, @M-Valts !