de: consider local_name only for namespaced tags in structs with $value
tafia/quick-xml pull request #736
Opened 2024-04-12 06:42 UTC by Xiphoseer

This updates the "not_in" check that decides whether to pass a new start tag within a struct to a $value field, to only consider the local part of a QName. It now uses the same decode_name function as the QNameDeserializer that is used for keys/fields already to ensure they stay in sync.

Using the namespaced name in serde (i.e. `#[serde(rename = "ns1:tag")]`) fails with ``Custom("missing field `ns1:tag`")`` today, so this will not break existing code.

Might help with #347

2024-04-12 07:28 UTC, Xiphoseer commented
Looks like I did not enable the "serialize" feature when running tests locally and got confused by the double negative

2024-04-12 15:58 UTC, Mingun requested changes
Could you test if this actually fixes #347? Add regression test into `./tests/serde-issues.rs`. Try to keep original code as much as possible to be sure that's user problem is actually solved, but instead of printing results use assertions. **That test is needed only if #347 is fixed.**

If your patch does not fix the error, then I would like to see a test which will demonstrate working of this fix, so it will not break in the future (you are also free to add it anyway even if regression test fit our needs).

I also interested to check how it behaves with serialization. Ideally, we should be able to deserialize serialized data. I'm not sure that this is always true now, but we strive for this. So if your patch fix that aspect, it also would be welcome to be presented in a test.

When test will demonstrate changes that was made, please add an entry to `Changelog.md` with a short description of what is fixed.

2024-04-12 19:21 UTC, Xiphoseer commented
Hey, thank you for the review. My case is probably closer to #212, but that was closed as a duplicate of #347.

I agree that a regression test would be useful so I'll add one when I find time for it. This change doesn't do anything to fix serialization, but it tries to improve upon the current behavior of _only considering the local part of a QName for deserialization_.

My actual case is as follows:

```xml
<ns1:parent>
    <ns1:field />
    <ns1:one />
</ns1:parent>
```
with the following data model
```
#[derive(Deserialize)]
#[serde[renameAll = "camelCase")]
enum Choice {
  One,
  Two
}

#[derive(Deserialize)]
struct Field;

#[derive(Deserialize)]
#[serde[renameAll = "camelCase")]
struct Parent {
  field: Field;
  #[serde(rename = "$value")]
  choice: Vec<Choice>,
}
```

Today, this will try to find "field" as a variant in "Choice" because the `not_in && has_value_field` case triggers when deserializing the struct.

With the change in this PR, it will correctly identify "field" as a key on the struct even for "ns1:field".

Renaming the field to "ns1:field" via serde does not work, which I guess is what #437 is about: The `not_in` would trigger but the `QNameDeserializer` will pick just the local part and fail to find the field so you get "missing field" errors.

I imagine that adding a toggle in `Deserializer` (use local name vs full name for `decode_name`) could be a backwards compatible change to resolve #437.

2024-04-29 17:42 UTC, Mingun commented
I checked, and this PR does not solve #347, but solve #683, because it actually does the same thing as #702.

Unfortunately, #683 and #347 seems to contradict each other. #347 requires to consider prefix part of a tag. Well, it should be possible to fix both issues, but this simple fix just solve the #683 case, but makes us a little more far from solving #347 (in particular, this change makes it impossible to deal with [that example](https://github.com/tafia/quick-xml/issues/347#issuecomment-1002362006)).

I would prefer to investigate possibilities to solve both cases (#683 and #347).

cc @leftmostcat

2024-05-07 19:16 UTC, leftmostcat commented
> I would prefer to investigate possibilities to solve both cases (#683 and #347).

Would it make sense to, unless the field is named `$text` or `$value`, parse the field name as an XML name and when deserializing, only compare local name to local name?

2024-05-13 07:04 UTC, Xiphoseer commented
FWIW this question sent me down a rabbit hole of "canonical" encodings of a namespaced name and/or QName into a single string in XML and whether it's appropriate to use that as a field identifier. [Turns out](https://www.w3.org/2001/tag/issues.html#rdfmsQnameUriMapping-6) that URI isn't the answer to that, instead the `{http://example.com/namespace}element` syntax seems to be established for it. If we assume the `@attribute` syntax is indeed [inspired by XPath](https://www.w3.org/TR/xpath-10/#path-abbrev), it might be reasonable to explore `Q{http://example.com/namespace}element` [from XPath 3.0](https://www.w3.org/TR/xpath-31/#doc-xpath31-BracedURILiteral) for namespace support.

Furthermore, I think it would be _wrong_ to use a serde field name of `ns1:element` unless going for a pure, pre <https://www.w3.org/TR/xml-names/> tag/attribute name handling mode. QNames are defined to be equivalent if their namespace and local name match, so attaching meaning to a specific prefix string value via making it part of the serde property would prevent its use for certain well-formed documents.

In my mind, #347 is more about making sure the _roundtrip_ works without different configuration for serialization and deserialization, regardless of any particular style of `#[serde(...)]` attributes. Suggesting that it's valid to _serialize_ with an arbitrary namespace prefix by annotating the field with a literal prefix `ns1:` not tied to some `xmlns:ns1` machinery is, in my understanding of XML Namespaces, a flawed assumption.

All that to say: After all that reading, I still think using the local part only is the correct first step toward full namespace support.

2024-05-13 15:10 UTC, Mingun commented
> Furthermore, I think it would be _wrong_ to use a serde field name of `ns1:element` unless going for a pure, pre https://www.w3.org/TR/xml-names/ tag/attribute name handling mode.

Yes, I agree with that.

> All that to say: After all that reading, I still think using the local part only is the correct first step toward full namespace support.

Yes, that's what I say in my previous comment.

2024-05-13 15:38 UTC, Xiphoseer commented
> > Furthermore, I think it would be _wrong_ to use a serde field name of `ns1:element` unless going for a pure, pre https://www.w3.org/TR/xml-names/ tag/attribute name handling mode.
> 
> Yes, I agree with that.
> 
> > All that to say: After all that reading, I still think using the local part only is the correct first step toward full namespace support.
> 
> Yes, that's what I say in my previous comment.

In that case, would it be possible to merge this PR as-is and do improvements to namespace handling as follow ups? Right now this bug (QNameDeserializer and not_in are inconsistent) severely reduces the usability of `$value`.

2024-05-13 16:47 UTC, Mingun commented
Yes, I'll combine your PR and #702, add tests and changelog. I'll plan to release new version soon, maybe this weekend. Unfortunately too many job at work and Kreia in KotOR2 is so intriguing. Anyway, thanks for your work!

2024-05-13 17:13 UTC, closed without merging