Fix DocType closing tag recognition in BufRead
tafia/quick-xml pull request #802
Opened 2024-09-19 03:43 UTC by BlueGreenMagick

Fixes #801

2024-09-19 05:10 UTC, BlueGreenMagick commented
Modified the code so that `balance_buf` is computed only once.

2024-09-19 15:30 UTC, Mingun requested changes
That PR will not fix the problem entirely, because correct DTD can contain unbalanced number of `<` and `>`, but I think that is rare case, so until proper fix will be implemented, a partial one also acceptable. The implementation, however, still may be improved. The problem here that we do not store state between invocations of `BangType::parse`. So the solution is to store balance inside `BangType::DocType`, then, I think, it will be unnecessary to calculate it over `buf` (because everything in `buf` previously was in `chunk`).

I also see the problem in the external `for i in memchr::memchr_iter(b'>', chunk)` loop. It will skip `<`s inside `chunk`s that does not contain `>`, so the balance will be calculated incorrectly. I think, if create a test carefully, it will catch such situation.

So I ask you to do the following changes:
- convert `BangType::DocType` -> `BangType::DocType(i32)`
- start with balance == 1 (it is `<` in `<!DOCTYPE`) here
https://github.com/tafia/quick-xml/blob/2f3824a1d265ac0b683aa485683ad00ddbc5c092/src/reader/mod.rs#L1031
- when calculate balance take into account saved balance
- emit event only when `BangType::DocType(0)` here
https://github.com/tafia/quick-xml/blob/2f3824a1d265ac0b683aa485683ad00ddbc5c092/src/reader/state.rs#L147
- add tests for the mentioned case (chunk with `<` + chunk with `>` which closes `<` from the first chunk). It is enough just craft such a string and use appropriate buffer size to slice string to desired chunks
- also add regression test from https://github.com/tafia/quick-xml/issues/590#issuecomment-1503927845
- try to check if this fixes #533. I think it should because it seems to be a duplicate of these issues, but need to check

2024-09-19 17:36 UTC, BlueGreenMagick commented
Thanks for the detailed feedback! I adjusted the PR.

> * start with balance == 1 (it is `<` in `<!DOCTYPE`) here
As the balance is calculated in up to chunk excluding current `>`, 1 is not added to balance initially.

> add tests for the mentioned case (chunk with < + chunk with > which closes < from the first chunk). It is enough just craft such a string and use appropriate buffer size to slice string to desired chunks

Are regression tests for issues 533, 590, 801 enough? Or are additional tests desired?

2024-09-19 17:53 UTC, Mingun approved these changes
> Are regression tests for issues 533, 590, 801 enough? Or are additional tests desired?

I'm not sure that tests still cover the case when we get four chunks with roughly such content:
1. `<!DOCTYPE`
2. `<` without any `>`
3. `>`, which would close `<` from point 2, not the doctype
4. `>` which should close doctype

If that case already covered, fine, although I would prefer to have test which explicitly guaranties such conditions (can tweak one of added regression tests for that).

And please add changelog entry to `Changelog.md` that people know that bug (#590) fixed. I'll close other as duplicate.

2024-09-19 17:53 UTC, Mingun commented on tests/issues.rs
> +}
Please put this test into `serde-issues.rs`. It compiles only when `serialize` feature is active so does not require feature gate.

2024-09-19 17:53 UTC, Mingun commented on src/reader/mod.rs
> +    DocType(i32),
Updating documentation also would be useful (language can be improved if required, I'm not native speaker):
```rust
    /// <!DOCTYPE...>. Contains a balance of `<` (+1) and `>` (-1)
    DocType(i32),
```

2024-09-19 17:58 UTC, Mingun commented
You also can squash all your changes if you wish

2024-09-20 06:03 UTC, BlueGreenMagick commented
Done! 

I adjusted regression test for issue801 so that all angle brackets are explicitly in different buffer (by lowering buffer size to 2 bytes).

I think it might be better (and easier with GitHub UI) to squash merge on your end, so others can follow the conversations and commits in the future.

2024-09-20 16:42 UTC, merged

2024-09-20 16:42 UTC, Mingun commented
Thanks!